[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Sigumo <kravchuk.ivan.5302@gmail.com>"]

[dependencies]
num = "0.4.1"
image = "0.23.12"
crossbeam = "0.8.2"
crossbeam-utils = "0.8"
num_cpus = "1.16.0"